CREATE TABLE `t1` (
  `a` INT(11) NOT NULL,
  PRIMARY KEY (`a`)
);

CREATE TABLE `t3` (
  `a` INT(11) NOT NULL DEFAULT '0',
  `b` INT(11) NOT NULL DEFAULT '0'
);

CREATE TABLE `user` (
  `id` INT(10) NOT NULL,
  `name` VARCHAR(20) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
);

